jwt:
  secretKey: a-string-secret-at-least-256-bits-long
#api gateway config
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://skysoft.com
            - name: Logging
            - name: Authentication
              args:
                enabled: false
            - name: Authorization
              args:
                enabled: true
                allowedRoles: ADMIN, SUPER_ADMIN
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Hama
            - name: Authentication
