eureka:
  client:
    service-url:
      defaultzone : http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
